document_type: relevé_bancaire
banque: NSIA
format: texte+tesseract

structure:
  champs_simples:

    numero_de_compte:
      anchor: "Numéro"
      direction: "right"
      regex: "\\d{19,20}"  # Dans l'extrait : 0100001260018912010

    
    nom_client:
      anchor: "Compte"
      direction: "right_xy"
      min_y: 400
      max_y: 500
      min_x: 950
      tolerance_y: 10
      regex: "\\w+"
      concat: true

    devise:
      anchor: "Devise"
      direction: "right"
      regex: "[A-Z]{3}"  # XOF
  
    periode_debut:
      anchor: "Du"
      direction: "right"
      regex: "\\d{2}/\\d{2}/\\d{4}"

    periode_fin:
      anchor: "Au"
      direction: "right"
      regex: "\\d{2}/\\d{2}/\\d{4}"
      
    solde_debut_periode:
      anchor_sequence: ["Solde", "Début", "Période"]
      direction: line_right
      min_y: 570     # couvre 580-581 et 765-766
      max_y: 770
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    total_debit:
      anchor_sequence: ["Total", "Débit"]
      direction: line_right
      min_y: 637     # couvre 637 et 820
      max_y: 830
      min_x: 950
      max_x: 1300
      concat: true
      regex: "^\\d{1,3}(?: \\d{3})*$"
      tolerance_y: 3

    total_credit:
      anchor_sequence: ["Total", "Crédit"]
      direction: line_right
      min_y: 690     # couvre 694-695 et 875-876
      max_y: 880
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    nombre_debit:
      anchor_sequence: ["Nombre", "Débit"]
      direction: line_right
      min_y: 740     # couvre 751-752 et 930-932
      max_y: 940
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    nombre_credit:
      anchor_sequence: ["Nombre", "Crédit"]
      direction: line_right
      min_y: 800     # couvre 808-809 et 985-987
      max_y: 990
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

  transactions:
    start_line_regex: "\\d{2}/\\d{2}/\\d{4}"  # détecte les lignes qui commencent par une date
    group_by_y_tolerance: 3
    columns:
      date_transaction:
        x_min: 0
        x_max: 150
        regex: "\\d{2}/\\d{2}/\\d{4}"
      detail_transaction:
        x_min: 151
        x_max: 950
      cheque_num:
        x_min: 951
        x_max: 1100
      agence:
        x_min: 1101
        x_max: 1250
      date_valeur:
        x_min: 1251
        x_max: 1400
        regex: "\\d{2}/\\d{2}/\\d{4}"
      debit:
        x_min: 1401
        x_max: 1600
        regex: "^\\d{1,3}( \\d{3})*$"
      credit:
        x_min: 1601
        x_max: 1800
        regex: "^\\d{1,3}( \\d{3})*$"
      solde:
        x_min: 1801
        x_max: 2100
        regex: "^\\d{1,3}( \\d{3})*$"


normalisation:
  montant:
    supprimer_espaces: true
    convertir_en_float: true
  date:
    format_source: "%d/%m/%Y"
    format_cible: "%Y-%m-%d"
  numero_de_compte:
    convertir_en_float: false
