python parsers/extract_data.py --pdf data/raw/nsia.pdf --config configs/nsia.releve.yaml 
python parsers/extract_data.py --pdf data/raw/NSIA2.pdf --config configs/nsia.releve.yaml 
python parsers/extract_data.py --pdf data/raw/sgbe.pdf --config configs/sgbe.releve.yaml 
python parsers/extract_data.py --pdf data/raw/coris.pdf --config configs/coris.releve.yaml 
python parsers/extract_data.py --pdf data/raw/cbao.pdf --config configs/cbao.releve.yaml 
python parsers/extract_data.py --pdf data/raw/RELEVE_UBA.pdf --config configs/uba_scan.releve.yaml
python parsers/extract_data.py --pdf data/raw/Relevés2_UBA.pdf --config configs/uba.releve.yaml 
python parsers/extract_data.py --pdf data/raw/RELEVE_BIIC.pdf --config configs/biic.releve.yaml 
python parsers/extract_data.py --pdf data/raw/ECOBANK.pdf --config configs/ecobank.releve.yaml 
python parsers/extract_data.py --pdf data/raw/TRESOR.pdf --config configs/tresor.releve.yaml