document_type: relevé_bancaire
banque: NSIA
format: texte+tesseract

crop_tables: true
preprocess_pdf: false
preprocess_tables: false

ocr:
  pdf:
    psm: 3
    oem: 3
  tables:
    psm: 12
    oem: 1


structure:
  champs_simples:

    numero_de_compte:
      anchor: "Numéro"
      direction: "right"
      regex: "\\d{19,20}"  # Dans l'extrait : 0100001260018912010

    
    nom_client:
      anchor: "Compte"
      direction: "right_xy"
      min_y: 400
      max_y: 500
      min_x: 950
      tolerance_y: 10
      regex: "\\w+"
      concat: true

    devise:
      anchor: "Devise"
      direction: "right"
      regex: "[A-Z]{3}"  # XOF
  
    periode_debut:
      anchor: "Du"
      direction: "right"
      regex: "\\d{2}/\\d{2}/\\d{4}"

    periode_fin:
      anchor: "Au"
      direction: "right"
      regex: "\\d{2}/\\d{2}/\\d{4}"
      
    solde_debut_periode:
      anchor_sequence: ["Solde", "Début", "Période"]
      direction: line_right
      min_y: 570     # couvre 580-581 et 765-766
      max_y: 770
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    total_debit:
      anchor_sequence: ["Total", "Débit"]
      direction: line_right
      min_y: 637     # couvre 637 et 820
      max_y: 830
      min_x: 950
      max_x: 1300
      concat: true
      regex: "^\\d{1,3}(?: \\d{3})*$"
      tolerance_y: 3

    total_credit:
      anchor_sequence: ["Total", "Crédit"]
      direction: line_right
      min_y: 690     # couvre 694-695 et 875-876
      max_y: 880
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    nombre_debit:
      anchor_sequence: ["Nombre", "Débit"]
      direction: line_right
      min_y: 740     # couvre 751-752 et 930-932
      max_y: 940
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

    nombre_credit:
      anchor_sequence: ["Nombre", "Crédit"]
      direction: line_right
      min_y: 800     # couvre 808-809 et 985-987
      max_y: 990
      min_x: 950
      max_x: 1250
      concat: true
      regex: "^[\\d\\s]+$"
      tolerance_y: 3

  transactions:
    source: "table"
    filter_contains:
      - "Date"
    start_line_regex: "\\d{2}/\\d{2}/\\d{4}"
    start_line_x_max: 300
    y_tolerance_above: 45
    y_tolerance_below: 50
    columns:
      date_transaction:
        x_min: 0
        x_max: 140
        regex: "\\d{2}/\\d{2}/\\d{4}"
      detail_transaction:
        x_min: 141
        x_max: 850
      cheque_num:
        x_min: 890
        x_max: 1050
      agence:
        x_min: 1060
        x_max: 1100
      date_valeur:
        x_min: 1160
        x_max: 1320
        regex: "\\d{2}/\\d{2}/\\d{4}"
      mouv_debit:
        x_min: 1430
        x_max: 1600
        regex: "^\\d{1,3}(?: \\d{3})*(?:,\\d{2})?$"
      mouv_credit:
        x_min: 1690
        x_max: 1930
        regex: "^\\d{1,3}(?: \\d{3})*(?:,\\d{2})?$"
      solde:
        x_min: 1931
        x_max: 2200
        regex: "^\\d{1,3}(?: \\d{3})*(?:,\\d{2})?$"


normalisation:
  montant:
    supprimer_espaces: true
    convertir_en_float: true
  date:
    format_source: "%d/%m/%Y"
    format_cible: "%Y-%m-%d"
  numero_de_compte:
    convertir_en_float: false
